"use client";

import { IconArrowRight, IconSparkles } from "@tabler/icons-react";
import Link from "next/link";
import { useState, type FormEvent } from "react";
import { authClient } from "../../lib/auth/client";

export default function SignUpPage() {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(null); const result = await authClient.signUp.email({ name, email, password }); if (result.error) setError(result.error.message ?? "註冊失敗，請稍後再試。"); else window.location.assign("/workspaces"); setLoading(false); }
  return <main className="grid min-h-screen bg-[#fbfbfa] lg:grid-cols-2"><section className="flex flex-col justify-between p-6 sm:p-10"><Link href="/" className="text-lg font-semibold tracking-tight">Proximate</Link><form onSubmit={submit} className="mx-auto w-full max-w-sm"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[#0f9f8a]">Get started</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">建立帳號</h1><p className="mt-3 text-sm leading-6 text-[#787774]">建立帳號後即可建立團隊工作區。</p><label className="mt-7 block text-sm font-medium">名稱<input required value={name} onChange={(event) => setName(event.target.value)} className="control-primary mt-2" /></label><label className="mt-4 block text-sm font-medium">Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="control-primary mt-2" /></label><label className="mt-4 block text-sm font-medium">密碼<input required minLength={8} type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="control-primary mt-2" /></label>{error && <p role="alert" className="mt-4 rounded-primary bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<button disabled={loading} type="submit" className="mt-6 flex w-full items-center justify-center gap-2 rounded-primary bg-[#0f9f8a] px-4 py-3 text-sm font-semibold text-white hover:bg-[#0b8978] disabled:opacity-60">{loading ? "建立中…" : "建立帳號"} <IconArrowRight size={18} /></button><p className="mt-5 text-center text-sm text-[#787774]">已經有帳號？ <Link href="/sign-in" className="font-medium text-[#0f9f8a] hover:underline">登入</Link></p></form><p className="text-xs text-[#9b9b97]">Proximate · thoughtful meetings, together</p></section><aside className="hidden bg-[#0f9f8a] p-10 text-white lg:flex lg:flex-col lg:justify-end"><IconSparkles size={34} /><h2 className="mt-6 max-w-md text-4xl font-semibold leading-tight">讓團隊的不同觀點，成為更好的決策。</h2><p className="mt-5 max-w-md text-white/70">建立工作區、邀請成員，讓每場會議都有共同脈絡。</p></aside></main>;
}
