"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState, type FormEvent } from "react";
import { AppShell } from "../../../../components/app-shell";
import { PageHeader } from "../../../../components/page-header";
import { TeamSubnav } from "../../../../components/team-subnav";
import { cancelInvitation, createInvitation, listInvitations, listTeamMembers, listTeams, removeTeamMember, updateTeamMember } from "../../../../lib/api/teams";
import type { Invitation, Team, TeamMember } from "../../../../types/api";

export default function WorkspaceMembersPage() {
  const { workspaceId } = useParams<{ workspaceId: string }>();
  const [team, setTeam] = useState<Team | null>(null); const [members, setMembers] = useState<TeamMember[]>([]); const [invitations, setInvitations] = useState<Invitation[]>([]); const [email, setEmail] = useState(""); const [role, setRole] = useState<"member" | "admin">("member"); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = () => Promise.all([listTeams(), listTeamMembers(workspaceId)]).then(async ([teams, result]) => { const current = teams.teams.find((item) => item.id === workspaceId) ?? null; setTeam(current); setMembers(result.members); setInvitations(current?.role === "admin" ? await listInvitations(workspaceId) : []); }).catch((e) => setMessage(e instanceof Error ? e.message : "無法讀取成員資料。"));
  useEffect(() => { void load(); }, [workspaceId]);
  async function invite(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (busy || !email.trim()) { if (!email.trim()) setMessage("請輸入已註冊帳號的 Email。"); return; } setBusy(true); setMessage(""); try { await createInvitation(workspaceId, { email: email.trim(), role }); setEmail(""); setMessage("邀請已建立；對方登入後會在站內看到邀請。"); void load(); } catch (e) { setMessage(e instanceof Error ? e.message : "建立邀請失敗。"); } finally { setBusy(false); } }
  return <AppShell><PageHeader eyebrow="Team" title={team ? `${team.name} 的成員` : "成員與邀請"} description="管理團隊中的角色，並以站內邀請加入新成員。" actions={<Link href={`/workspaces/${workspaceId}/meetings`}>查看團隊會議</Link>} /><div className="mt-8"><TeamSubnav teamId={workspaceId} active="members" /></div>{message && <p role="status" className="mt-5 rounded-xl bg-[#e7f7ef] px-4 py-3 text-sm text-[#087e6d]">{message}</p>}<div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><section className="rounded-2xl border bg-white p-6"><h2 className="font-semibold">目前成員</h2><div className="mt-5 space-y-3">{members.map((member) => <article key={member.user_id} className="flex items-center gap-3 rounded-xl border p-4"><div className="min-w-0 flex-1"><h3 className="truncate font-medium">{member.display_name || "未設定名稱"}</h3><p className="text-xs text-[#787774]">{member.role === "admin" ? "管理員" : "成員"}</p></div>{team?.role === "admin" && <><select value={member.role} onChange={(e) => void updateTeamMember(workspaceId, member.user_id, { role: e.target.value }).then(() => void load())} className="control-primary w-auto py-2 text-xs"><option value="member">成員</option><option value="admin">管理員</option></select><button type="button" onClick={() => void removeTeamMember(workspaceId, member.user_id).then(() => void load())} className="text-xs text-red-700">移除</button></>}</article>)}</div></section><aside><section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">邀請成員</h2><p className="mt-2 text-sm text-[#787774]">輸入已註冊帳號的 Email；不會顯示帳號清單或寄送 Email。</p><form onSubmit={invite} className="mt-4 space-y-3"><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="control-primary" placeholder="name@example.com" /><select value={role} onChange={(e) => setRole(e.target.value as "member" | "admin")} className="control-primary"><option value="member">成員</option><option value="admin">管理員</option></select><button disabled={busy} className="w-full rounded-lg bg-[#0f9f8a] px-4 py-2.5 text-sm font-semibold text-white">{busy ? "建立中…" : "建立邀請"}</button></form></section><section className="mt-6 rounded-2xl border bg-white p-5"><h2 className="font-semibold">待接受邀請</h2>{invitations.filter((i) => i.status === "pending").map((item) => <div key={item.id} className="mt-3 rounded-xl bg-[#f7f7f5] p-3"><p className="truncate text-sm">{item.recipient_name || item.email || "未設定名稱"}</p><button type="button" onClick={() => void cancelInvitation(workspaceId, item.id).then(() => void load())} className="mt-2 text-xs text-red-700">取消邀請</button></div>)}</section></aside></div></AppShell>;
}
