import { IconAlertTriangle, IconMicrophone, IconShieldCheck } from "@tabler/icons-react";
import Link from "next/link";
import { AppShell } from "../../../../components/app-shell";
import { MeetingWorkspaceHeader } from "../../../../components/meeting-workspace-header";

export default async function AudioSetupPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  return <AppShell><MeetingWorkspaceHeader meetingId={id} phase="audio" /><div className="mx-auto mt-8 max-w-2xl space-y-5"><section className="rounded-2xl border border-[#e6e6e3] bg-white p-6"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#e7f7ef] text-[#1d6b4d]"><IconMicrophone size={23} /></div><h2 className="mt-5 text-xl font-semibold">開啟個人音訊偵測</h2><p className="mt-2 text-sm leading-6 text-[#787774]">你同意後，Capture Page 只會傳送你的麥克風聲音供逐字稿與即時分析使用。MVP 不長期保存原始音訊。</p><label className="mt-5 flex items-start gap-3 rounded-xl bg-[#f7f7f5] p-4 text-sm"><input className="mt-1 h-4 w-4 accent-[#2f6f5e]" type="checkbox" /><span><strong>我了解並同意收音範圍</strong><span className="mt-1 block text-[#787774]">離開此頁後，Capture Page 需要保持開啟以維持收音狀態。</span></span></label><button type="button" className="mt-5 w-full rounded-lg bg-[#2f6f5e] px-4 py-3 text-sm font-semibold text-white">允許麥克風並開始偵測</button></section><section className="rounded-2xl border border-[#e6e6e3] bg-white p-5"><div className="flex gap-3"><IconShieldCheck size={20} className="shrink-0 text-[#2f6f5e]" /><div><h2 className="font-semibold">目前狀態</h2><p className="mt-1 text-sm text-[#787774]">尚未請求瀏覽器麥克風權限。</p></div></div></section><section className="flex gap-3 rounded-2xl border border-[#f0dca5] bg-[#fffaf0] p-5 text-sm text-[#715b1e]"><IconAlertTriangle size={20} className="shrink-0" />背景分頁可能因省電機制停止收音；開始後請保持此 Capture Page 開啟。</section><Link href={`/meetings/${id}/live`} className="block text-center text-sm text-[#2f6f5e] hover:underline">改用瀏覽器 Live fallback</Link></div></AppShell>;
}
