"use client";
import { IconCircle, IconHandStop, IconLock, IconMessageCircle2, IconRobot, IconUsers } from "@tabler/icons-react";
import { use } from "react";
import { authClient } from "../../../../lib/auth/client";

export default function AddonPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const { data: session, isPending } = authClient.useSession();
  const identity = session?.user?.name ?? session?.user?.email;
  return <main className="min-h-screen bg-[#fbfbfa] p-3 text-[#1f1f1f]"><div className="mx-auto max-w-3xl overflow-hidden rounded-xl border border-[#e1e1de] bg-white"><header className="flex items-center justify-between border-b border-[#e9e9e6] px-4 py-3"><div><p className="text-sm font-semibold">Proximate</p><p className="text-xs text-[#8b8b87]">Meeting #{id}</p></div><span className="inline-flex items-center gap-1 text-xs text-[#0f9f8a]"><IconCircle size={8} fill="currentColor" />{isPending ? "確認登入狀態…" : identity ? `已登入 ${identity}` : "請先在主程式登入"}</span></header><div className="grid gap-4 p-4 md:grid-cols-[1.15fr_0.85fr]"><section className="space-y-4"><div className="rounded-xl bg-[#f7f7f5] p-4"><p className="text-xs font-semibold uppercase tracking-wide text-[#8b8b87]">目前議題</p><h1 className="mt-2 font-semibold">確認 MVP 的發言與共識機制</h1><p className="mt-2 text-sm leading-6 text-[#787774]">Main Agent 正在整理討論中出現的風險、反例與未解問題。</p></div><div className="rounded-xl border border-[#e6e6e3] p-4"><div className="flex items-start gap-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[#e7f7ef] text-[#1d6b4d]"><IconRobot size={18} /></span><div><p className="font-medium">Proximate 想發言</p><p className="mt-1 text-sm leading-6 text-[#787774]">這個門檻可能會讓少數觀點被忽略。是否要保留「少數意見提醒」？</p></div></div><div className="mt-4 flex flex-wrap gap-2"><button className="rounded-lg bg-[#0f9f8a] px-3 py-2 text-xs font-semibold text-white">支持</button><button className="rounded-lg border border-[#dededb] px-3 py-2 text-xs font-medium">稍後</button><button className="rounded-lg border border-[#dededb] px-3 py-2 text-xs font-medium">忽略</button></div><p className="mt-3 text-xs text-[#787774]">4 / 6 人支持 · 尚未達到 75% 門檻</p></div></section><aside className="space-y-4"><section className="rounded-xl border border-[#e6e6e3] p-4"><div className="flex items-center gap-2"><IconMessageCircle2 size={17} className="text-[#0f9f8a]" /><h2 className="text-sm font-semibold">Personal Sidekick</h2><IconLock size={14} className="ml-auto text-[#8b8b87]" /></div><p className="mt-3 text-sm leading-6 text-[#787774]">僅你可見。你先前曾擔心這個門檻會壓低少數意見。</p><button className="mt-3 text-xs font-semibold text-[#0f9f8a]">整理為我的觀點</button></section><section className="rounded-xl border border-[#e6e6e3] p-4"><div className="flex items-center gap-2"><IconHandStop size={17} className="text-[#0f9f8a]" /><h2 className="text-sm font-semibold">Voice Bot</h2></div><p className="mt-3 text-sm text-[#787774]">等待團隊支持門檻。</p></section><p className="flex items-center gap-2 text-xs text-[#8b8b87]"><IconUsers size={15} />所有參與者都能看到公開狀態。</p></aside></div></div></main>;
}
