import { IconCalendar, IconChevronDown, IconPlus, IconSparkles, IconUsers } from "@tabler/icons-react";
import Link from "next/link";
import { AppShell } from "../../../components/app-shell";
import { PageHeader } from "../../../components/page-header";

const fieldClass = "mt-2 w-full rounded-lg border border-[#dededb] bg-white px-3 py-2.5 text-sm outline-none placeholder:text-[#a5a5a1] focus:border-[#2f6f5e] focus:ring-2 focus:ring-[#2f6f5e]/15";

export default function NewMeetingPage() {
  return <AppShell><PageHeader eyebrow="New meeting" title="建立會議" description="設定本場討論的基本資訊、主持人與 AI 參與方式。送出功能會在正式會議 API 確認後啟用。" />
    <div className="mt-8 grid max-w-5xl gap-6 lg:grid-cols-[minmax(0,1fr)_290px]"><form className="space-y-6 rounded-2xl border border-[#e6e6e3] bg-white p-5 sm:p-7"><section><h2 className="font-semibold">會議資訊</h2><label className="mt-5 block text-sm font-medium">會議名稱<input className={fieldClass} placeholder="例如：產品方向校準會議" /></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">開始時間<div className="relative"><input className={fieldClass} type="datetime-local" /><IconCalendar className="pointer-events-none absolute right-3 top-4 text-[#8b8b87]" size={17} /></div></label><label className="text-sm font-medium">Google Meet 連結<input className={fieldClass} placeholder="https://meet.google.com/..." /></label></div></section>
      <section className="border-t border-[#ededeb] pt-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold">議程</h2><p className="mt-1 text-sm text-[#787774]">將議題依討論順序排列。</p></div><button type="button" className="inline-flex items-center gap-1 text-sm font-medium text-[#2f6f5e]"><IconPlus size={17} />新增議題</button></div><div className="mt-4 rounded-xl border border-dashed border-[#d8d8d5] p-4 text-sm text-[#787774]">尚未加入議題。建立後可在會前準備頁補充。</div></section>
      <section className="border-t border-[#ededeb] pt-6"><h2 className="font-semibold">會議設定</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">本場主持人<div className="relative"><select className={fieldClass} defaultValue="yanji"><option value="yanji">Yanji Chen</option></select><IconChevronDown className="pointer-events-none absolute right-3 top-4" size={16} /></div></label><label className="text-sm font-medium">發言支持門檻<div className="relative"><select className={fieldClass} defaultValue="50"><option value="50">50% 支持</option></select><IconChevronDown className="pointer-events-none absolute right-3 top-4" size={16} /></div></label></div></section>
      <div className="flex flex-col-reverse justify-end gap-3 border-t border-[#ededeb] pt-6 sm:flex-row"><Link href="/dashboard" className="rounded-lg px-4 py-2.5 text-center text-sm font-medium text-[#5f5f5b] hover:bg-[#f4f4f2]">取消</Link><button type="button" className="rounded-lg bg-[#2f6f5e] px-4 py-2.5 text-sm font-semibold text-white">儲存會議草稿</button></div></form>
      <aside className="h-fit rounded-2xl border border-[#e6e6e3] bg-[#f7f7f5] p-5"><div className="flex items-center gap-2 font-semibold"><IconSparkles size={19} className="text-[#2f6f5e]" />AI 參與設定</div><p className="mt-2 text-sm leading-6 text-[#787774]">本場會議將啟用 Main Agent 與每位成員的 Personal Sidekick。</p><div className="mt-5 space-y-3"><div className="rounded-xl bg-white p-3"><p className="text-sm font-medium">主持人</p><p className="mt-1 text-xs text-[#787774]">可暫停或否決 AI 發言。</p></div><div className="rounded-xl bg-white p-3"><p className="text-sm font-medium">參與者 <IconUsers className="inline" size={16} /></p><p className="mt-1 text-xs text-[#787774]">達到門檻後，AI 才會請求發言。</p></div></div></aside></div>
  </AppShell>;
}
