"use client";

import { IconCalendarEvent, IconCheck, IconMessageCircle, IconPlayerPlay, IconRobot, IconUsersGroup } from "@tabler/icons-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState, type FormEvent } from "react";
import { AppShell } from "../../../../components/app-shell";
import { MeetingWorkspaceHeader } from "../../../../components/meeting-workspace-header";
import { listAgendaItems, updateAgendaItem } from "../../../../lib/api/agenda";
import { createDelegate, listDelegates } from "../../../../lib/api/delegates";
import { createConsensus, createPersonalMessage, listPersonalMessages } from "../../../../lib/api/meeting-features";
import { cancelMeeting, endMeeting, getMeeting, startMeeting } from "../../../../lib/api/meetings";
import { listParticipants } from "../../../../lib/api/participants";
import { listTeamMembers } from "../../../../lib/api/teams";
import type { AgendaItem, DelegateProfile, MeetingSummary, Participant, PersonalMessage, TeamMember } from "../../../../types/api";

const labels: Record<string, string> = { draft: "草稿", scheduled: "已排程", in_progress: "進行中", completed: "已結束", cancelled: "已取消" };
const statusClass: Record<string, string> = { draft: "bg-slate-100 text-slate-700", scheduled: "bg-blue-50 text-blue-700", in_progress: "bg-amber-50 text-amber-800", completed: "bg-emerald-50 text-emerald-700", cancelled: "bg-rose-50 text-rose-700" };
const errorMessage = (cause: unknown, fallback: string) => cause instanceof Error ? cause.message : fallback;

function Discussion({ meetingId, item, onSummary }: { meetingId: string; item: AgendaItem; onSummary: (value: string) => void }) {
  const [messages, setMessages] = useState<PersonalMessage[]>([]); const [draft, setDraft] = useState(""); const [open, setOpen] = useState(false); const [summary, setSummary] = useState("");
  useEffect(() => { listPersonalMessages(meetingId).then(setMessages).catch(() => undefined); }, [meetingId]);
  const related = messages.filter((message) => message.content.startsWith(`[議程：${item.title}]`));
  async function send(event: FormEvent) { event.preventDefault(); if (!draft.trim()) return; try { const message = await createPersonalMessage(meetingId, `[議程：${item.title}] ${draft.trim()}`); setMessages((current) => [...current, message]); setDraft(""); setOpen(true); } catch { /* message error does not block the page */ } }
  function summarize() { const result = `「${item.title}」的個人討論已整理為 ${related.length} 則觀點；請在會議中確認限制與下一步。`; setSummary(result); onSummary(result); }
  return <div className="mt-3 rounded-xl bg-[#f7f7f5] p-3"><button type="button" onClick={() => setOpen((value) => !value)} className="inline-flex items-center gap-2 text-sm font-medium text-[#087e6d]"><IconMessageCircle size={16} />{open ? "收起與 Agent 的討論" : "和我的 Agent 討論這個議題"}</button>{open && <div className="mt-3"><div className="max-h-44 space-y-2 overflow-y-auto">{related.map((message) => <p key={message.id} className="rounded-lg bg-white p-2 text-sm leading-5">{message.content.replace(`[議程：${item.title}] `, "")}</p>)}{related.length === 0 && <p className="text-xs text-[#787774]">寫下疑慮、限制或希望；這些內容只屬於你。</p>}</div><form onSubmit={send} className="mt-3 flex gap-2"><input value={draft} onChange={(event) => setDraft(event.target.value)} className="control-primary min-w-0 flex-1 text-sm" placeholder="輸入想和 Agent 討論的內容" /><button type="submit" className="rounded-lg bg-[#0f9f8a] px-3 text-sm font-semibold text-white">送出</button></form><button type="button" disabled={!related.length} onClick={summarize} className="mt-3 rounded-lg border border-[#cde5df] px-3 py-2 text-xs font-semibold text-[#087e6d] disabled:opacity-40">產生討論總結</button>{summary && <p className="mt-2 rounded-lg border border-[#9ddbc8] bg-white p-3 text-sm">{summary}</p>}</div>}</div>;
}

export default function PreparePage() {
  const { id } = useParams<{ id: string }>(); const [meeting, setMeeting] = useState<MeetingSummary | null>(null); const [agenda, setAgenda] = useState<AgendaItem[]>([]); const [participants, setParticipants] = useState<Participant[]>([]); const [members, setMembers] = useState<TeamMember[]>([]); const [delegates, setDelegates] = useState<DelegateProfile[]>([]); const [summaries, setSummaries] = useState<Record<string, string>>({}); const [delegateEnabled, setDelegateEnabled] = useState(false); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  async function refresh() { const current = await getMeeting(id); const [agendaResult, participantResult, delegateResult, teamResult] = await Promise.all([listAgendaItems(id), listParticipants(id), listDelegates(id), listTeamMembers(current.team_id)]); setMeeting(current); setAgenda(agendaResult.items); setParticipants(participantResult.participants); setDelegates(delegateResult); setMembers(teamResult.members); setDelegateEnabled(delegateResult.length > 0); }
  useEffect(() => { let active = true; refresh().catch((cause) => active && setError(errorMessage(cause, "無法讀取會議資料。"))).finally(() => active && setLoading(false)); return () => { active = false; }; }, [id]);
  async function run(action: () => Promise<unknown>, success: string) { setBusy(true); setError(""); setNotice(""); try { await action(); setNotice(success); await refresh(); } catch (cause) { setError(errorMessage(cause, "操作失敗，請稍後再試。")); } finally { setBusy(false); } }
  if (loading) return <AppShell><p className="text-sm text-[#787774]">正在準備會議…</p></AppShell>;
  if (!meeting) return <AppShell><p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error || "找不到此會議。"}</p></AppShell>;
  const canStart = meeting.status === "draft" || meeting.status === "scheduled"; const delegateContext = Object.values(summaries).join("\n"); const participantName = (userId: string) => members.find((member) => member.user_id === userId)?.display_name || "未設定名稱的成員";
  return <AppShell><MeetingWorkspaceHeader phase="prepare" title={meeting.title} /><div className="mt-6 flex flex-wrap items-center gap-3 rounded-2xl border border-[#e6e6e3] bg-white p-4"><span className={`rounded-full px-3 py-1 text-sm font-semibold ${statusClass[meeting.status] ?? statusClass.draft}`}>{labels[meeting.status] ?? meeting.status}</span><span className="inline-flex items-center gap-2 text-sm text-[#787774]"><IconCalendarEvent size={16} />{meeting.scheduled_at ? new Date(meeting.scheduled_at).toLocaleString("zh-TW") : "尚未設定時間"}</span><div className="ml-auto flex flex-wrap gap-2">{canStart && <button type="button" disabled={busy} onClick={() => void run(() => startMeeting(id), "會議已開始。取消只適用於尚未開始的會議。")} className="inline-flex items-center gap-1 rounded-lg bg-[#0f9f8a] px-3 py-2 text-sm font-semibold text-white disabled:opacity-60"><IconPlayerPlay size={16} />開始會議</button>}{meeting.status === "in_progress" && <button type="button" disabled={busy} onClick={() => void run(() => endMeeting(id), "會議已結束。") } className="inline-flex items-center gap-1 rounded-lg bg-[#1f1f1f] px-3 py-2 text-sm font-semibold text-white"><IconCheck size={16} />結束會議</button>}{canStart && <button type="button" disabled={busy} onClick={() => void run(() => cancelMeeting(id), "會議已取消；開始後請使用「結束會議」。")} className="rounded-lg border border-rose-200 px-3 py-2 text-sm font-medium text-rose-700">取消未開始的會議</button>}</div></div>{(notice || error) && <p role={error ? "alert" : "status"} className={`mt-4 rounded-xl px-4 py-3 text-sm ${error ? "bg-red-50 text-red-700" : "bg-[#e7f7ef] text-[#087e6d]"}`}>{error || notice}</p>}
    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><main className="space-y-6"><section className="rounded-2xl border border-[#e6e6e3] bg-white p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">議程與 Agent 討論</h2><p className="mt-1 text-sm leading-6 text-[#787774]">每位參與者看到同一組議程，並可針對每一題和自己的 Agent 多輪討論。完成後先確認個人總結，再送到 Review。</p></div><span className="text-sm text-[#787774]">{agenda.length} 項</span></div><ol className="mt-5 space-y-3">{agenda.map((item) => <li key={item.id} className="rounded-xl border border-[#ededeb] p-4"><div className="flex items-start gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#e7f7ef] text-sm font-semibold text-[#087e6d]">{item.position}</span><div className="min-w-0 flex-1"><input defaultValue={item.title} onBlur={(event) => { const title = event.target.value.trim(); if (title && title !== item.title) void run(() => updateAgendaItem(id, item.id, { title }), "已更新議程。"); }} className="w-full bg-transparent text-sm font-medium outline-none" aria-label="議程標題" /><select value={item.status} onChange={(event) => void run(() => updateAgendaItem(id, item.id, { status: event.target.value }), "已更新議程狀態。")} className="mt-2 bg-transparent text-xs text-[#787774]"><option value="pending">待討論</option><option value="in_progress">討論中</option><option value="completed">已完成</option></select></div></div><Discussion meetingId={id} item={item} onSummary={(value) => setSummaries((current) => ({ ...current, [item.id]: value }))} />{summaries[item.id] && <button type="button" disabled={busy} onClick={() => void run(() => createConsensus(id, summaries[item.id]), "已送到 Review，待你確認是否成為正式共識。") } className="mt-3 rounded-lg bg-[#0f9f8a] px-3 py-2 text-xs font-semibold text-white">確認並送到 Review</button>}</li>)}</ol></section>
      <section className="rounded-2xl border border-[#e6e6e3] bg-white p-5 sm:p-6"><div className="flex items-center gap-2"><IconRobot className="text-[#0f9f8a]" size={20} /><h2 className="text-lg font-semibold">缺席代理（可選）</h2></div><p className="mt-2 text-sm leading-6 text-[#787774]">代理會根據你已確認的議前討論內容協助提醒；不會投票、承諾或替你做決策。</p><label className="mt-4 flex items-center gap-3 rounded-xl bg-[#f7f7f5] p-3 text-sm"><input type="checkbox" checked={delegateEnabled} onChange={(event) => setDelegateEnabled(event.target.checked)} className="accent-[#0f9f8a]" /><span>本場由我的 Agent 依已確認的討論總結協助提醒</span></label><button type="button" disabled={!delegateEnabled || !delegateContext || busy || delegates.length > 0} onClick={() => void run(() => createDelegate(id, { stance: delegateContext }), "缺席代理已依目前的討論總結設定。") } className="mt-4 rounded-lg border border-[#cde5df] px-3 py-2 text-sm font-semibold text-[#087e6d] disabled:cursor-not-allowed disabled:opacity-40">{delegates.length ? "已設定缺席代理" : "儲存缺席代理"}</button>{delegateEnabled && !delegateContext && !delegates.length && <p className="mt-2 text-xs text-amber-700">請先至少產生一則議程討論總結，代理才有可遵循的內容。</p>}</section></main>
      <aside className="space-y-6"><section className="rounded-2xl border border-[#e6e6e3] bg-white p-5"><div className="flex items-center gap-2"><IconUsersGroup className="text-[#0f9f8a]" size={20} /><h2 className="font-semibold">本場參與者</h2></div><p className="mt-2 text-sm text-[#787774]">建立會議時已選定；此頁只顯示安排。</p><div className="mt-4 space-y-2">{participants.map((participant) => <div key={participant.user_id} className="flex items-center justify-between gap-3 rounded-xl bg-[#f7f7f5] p-3"><span className="text-sm font-medium">{participantName(participant.user_id)}</span><span className="text-xs text-[#787774]">{participant.attendance_status === "left" ? "無法出席" : participant.attendance_status === "joined" ? "將出席" : "待確認"}</span></div>)}{participants.length === 0 && <p className="rounded-xl bg-[#f7f7f5] p-3 text-sm text-[#787774]">建立時尚未選擇參與者。</p>}</div></section><Link href={`/meetings/${id}/addon`} className="block rounded-xl border border-[#dededb] px-4 py-3 text-center text-sm font-medium hover:bg-[#f7f7f5]">開啟 Meet Add-on</Link></aside></div>
  </AppShell>;
}
