import { IconArrowUpRight, IconMessageCircle2, IconNotes, IconSparkles } from "@tabler/icons-react";
import Link from "next/link";
import { AppShell } from "../../../../components/app-shell";
import { MeetingWorkspaceHeader } from "../../../../components/meeting-workspace-header";

export default async function PreparePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  return <AppShell><MeetingWorkspaceHeader meetingId={id} phase="prepare" /><div className="mt-7 grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-6"><section className="rounded-2xl border border-[#e6e6e3] bg-white p-5 sm:p-6"><div className="flex items-center gap-2"><IconNotes size={19} className="text-[#2f6f5e]" /><h2 className="font-semibold">Main Agent Brief</h2></div><p className="mt-4 text-sm leading-7 text-[#5f5f5b]">本場會議將聚焦於產品方向、第一版範圍與團隊分工。先確認不可妥協的需求，再討論可延後處理的項目。</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-[#f7f7f5] p-4"><p className="text-xs font-semibold uppercase tracking-wide text-[#8b8b87]">待決問題</p><p className="mt-2 text-sm font-medium">Voice Bot 的介入門檻如何設定？</p></div><div className="rounded-xl bg-[#f7f7f5] p-4"><p className="text-xs font-semibold uppercase tracking-wide text-[#8b8b87]">已發現分歧</p><p className="mt-2 text-sm font-medium">會中 UI 的優先入口：Add-on 或 fallback。</p></div></div></section><section className="rounded-2xl border border-[#e6e6e3] bg-white p-5 sm:p-6"><h2 className="font-semibold">議程</h2><ol className="mt-4 space-y-3">{["確認 MVP 成功條件", "設定 AI 角色與發言政策", "分配下一步行動項目"].map((item, index) => <li key={item} className="flex gap-3 rounded-xl border border-[#ededeb] px-4 py-3 text-sm"><span className="font-semibold text-[#2f6f5e]">0{index + 1}</span>{item}</li>)}</ol></section></div><aside className="rounded-2xl border border-[#e6e6e3] bg-white"><div className="border-b border-[#ededeb] p-5"><div className="flex items-center gap-2"><IconSparkles size={19} className="text-[#2f6f5e]" /><h2 className="font-semibold">Personal Sidekick</h2></div><p className="mt-2 text-xs text-[#787774]">僅你可見</p></div><div className="space-y-3 p-5 text-sm"><div className="rounded-xl bg-[#f2f6f4] p-3 leading-6">你可以先整理自己的觀點；公開前會請你確認內容。</div><div className="ml-7 rounded-xl bg-[#f7f7f5] p-3 text-[#787774]">我擔心 AI 發言會打斷討論節奏。</div></div><div className="border-t border-[#ededeb] p-4"><button type="button" className="flex w-full items-center justify-between rounded-lg border border-[#dcdcd8] px-3 py-2.5 text-left text-sm text-[#8b8b87]"><span>輸入你的想法…</span><IconMessageCircle2 size={18} /></button></div></aside></div><div className="mt-7 flex flex-wrap gap-3"><Link href={`/meetings/${id}/audio-setup`} className="inline-flex items-center gap-2 rounded-lg bg-[#2f6f5e] px-4 py-2.5 text-sm font-semibold text-white">設定收音 <IconArrowUpRight size={17} /></Link><Link href={`/meetings/${id}/addon`} className="rounded-lg border border-[#dededb] px-4 py-2.5 text-sm font-medium hover:bg-[#f7f7f5]">開啟 Meet Add-on 預覽</Link></div></AppShell>;
}
