"use client";

import { IconArrowUpRight, IconCalendar, IconCheck, IconPlayerPlay, IconPlus, IconRobot, IconSparkles, IconTrash, IconUsersGroup } from "@tabler/icons-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState, type FormEvent } from "react";
import { AppShell } from "../../../../components/app-shell";
import { MeetingWorkspaceHeader } from "../../../../components/meeting-workspace-header";
import { PersonalSidekickPanel } from "../../../../components/personal-sidekick-panel";
import { addAgendaItem, listAgendaItems, removeAgendaItem, updateAgendaItem } from "../../../../lib/api/agenda";
import { createDelegate, listDelegates } from "../../../../lib/api/delegates";
import { createMeetingBrief, cancelMeeting, endMeeting, getMeeting, startMeeting, updateMeeting } from "../../../../lib/api/meetings";
import { addParticipant, listParticipants, removeParticipant, updateParticipant } from "../../../../lib/api/participants";
import { listTeamMembers } from "../../../../lib/api/teams";
import type { AgendaItem, DelegateProfile, MeetingBrief, MeetingSummary, Participant, TeamMember } from "../../../../types/api";

const levelOptions = [{ id: "low", label: "低介入", description: "只有被詢問或高風險時才提醒" }, { id: "medium", label: "適度提醒", description: "重要的新風險與未決問題才舉手" }, { id: "high", label: "積極補充", description: "較常提出反例、替代方案與歷史提醒" }];
const statusLabels: Record<string, string> = { draft: "草稿", scheduled: "已排程", in_progress: "進行中", completed: "已結束", cancelled: "已取消" };
const inputClass = "control-primary mt-2 text-sm";
const errorMessage = (cause: unknown, fallback: string) => cause instanceof Error ? cause.message : fallback;

export default function PreparePage() {
  const { id } = useParams<{ id: string }>();
  const [meeting, setMeeting] = useState<MeetingSummary | null>(null);
  const [agenda, setAgenda] = useState<AgendaItem[]>([]);
  const [participants, setParticipants] = useState<Participant[]>([]);
  const [members, setMembers] = useState<TeamMember[]>([]);
  const [brief, setBrief] = useState<MeetingBrief | null>(null);
  const [delegates, setDelegates] = useState<DelegateProfile[]>([]);
  const [agendaTitle, setAgendaTitle] = useState("");
  const [selectedMember, setSelectedMember] = useState("");
  const [delegateEnabled, setDelegateEnabled] = useState(false);
  const [stance, setStance] = useState("");
  const [constraints, setConstraints] = useState("");
  const [mustRaise, setMustRaise] = useState("");
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");

  async function refresh() {
    const current = await getMeeting(id);
    const [agendaResult, participantResult, delegateResult] = await Promise.all([listAgendaItems(id), listParticipants(id), listDelegates(id)]);
    setMeeting(current); setAgenda(agendaResult.items); setParticipants(participantResult.participants); setDelegates(delegateResult);
    listTeamMembers(current.team_id).then((result) => setMembers(result.members)).catch(() => setMembers([]));
  }
  useEffect(() => { let active = true; refresh().catch((cause) => active && setError(errorMessage(cause, "無法讀取會議資料。"))).finally(() => active && setLoading(false)); return () => { active = false; }; }, [id]);
  async function run(action: () => Promise<void>, success: string) { setBusy(true); setError(""); setNotice(""); try { await action(); setNotice(success); await refresh(); } catch (cause) { setError(errorMessage(cause, "操作失敗，請稍後再試。")); } finally { setBusy(false); } }
  async function addAgenda(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!agendaTitle.trim()) return; await run(async () => { await addAgendaItem(id, { position: agenda.length + 1, title: agendaTitle.trim() }); setAgendaTitle(""); }, "已新增議程。"); }
  async function generateBrief() { await run(async () => { const result = await createMeetingBrief(id); setBrief(result); }, "會前 Brief 已更新。"); }
  async function saveDelegate(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!delegateEnabled || !stance.trim()) return; await run(async () => { await createDelegate(id, { stance: stance.trim(), constraints: constraints.trim() || undefined, must_raise: mustRaise.trim() || undefined }); setStance(""); setConstraints(""); setMustRaise(""); setDelegateEnabled(false); }, "已建立你的缺席代理規則。"); }
  const memberName = (userId: string) => members.find((member) => member.user_id === userId)?.display_name || "會議參與者";

  if (loading) return <AppShell><p className="text-sm text-[#787774]">正在準備會議工作區…</p></AppShell>;
  if (!meeting) return <AppShell><p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error || "找不到此會議。"}</p></AppShell>;
  const canStart = meeting.status === "draft" || meeting.status === "scheduled";

  return <AppShell><MeetingWorkspaceHeader phase="prepare" title={meeting.title} />
    <div className="mt-6 flex flex-wrap items-center gap-3 rounded-2xl border border-[#e6e6e3] bg-white p-4"><span className="rounded-full bg-[#e7f7ef] px-3 py-1 text-sm font-medium text-[#087e6d]">{statusLabels[meeting.status] ?? meeting.status}</span><span className="inline-flex items-center gap-2 text-sm text-[#787774]"><IconCalendar size={16} />{meeting.scheduled_at ? new Date(meeting.scheduled_at).toLocaleString("zh-TW") : "尚未設定時間"}</span><div className="ml-auto flex flex-wrap gap-2">{canStart && <button type="button" disabled={busy} onClick={() => void run(async () => { await startMeeting(id); }, "會議已開始。") } className="inline-flex items-center gap-1 rounded-lg bg-[#0f9f8a] px-3 py-2 text-sm font-semibold text-white disabled:opacity-60"><IconPlayerPlay size={16} />開始會議</button>}{meeting.status === "in_progress" && <button type="button" disabled={busy} onClick={() => void run(async () => { await endMeeting(id); }, "會議已結束。") } className="inline-flex items-center gap-1 rounded-lg bg-[#1f1f1f] px-3 py-2 text-sm font-semibold text-white disabled:opacity-60"><IconCheck size={16} />結束會議</button>}{canStart && <button type="button" disabled={busy} onClick={() => void run(async () => { await cancelMeeting(id); }, "會議已取消。") } className="rounded-lg border border-red-200 px-3 py-2 text-sm font-medium text-red-700 disabled:opacity-60">取消會議</button>}</div></div>
    {(notice || error) && <p role={error ? "alert" : "status"} className={`mt-4 rounded-xl px-4 py-3 text-sm ${error ? "bg-red-50 text-red-700" : "bg-[#e7f7ef] text-[#087e6d]"}`}>{error || notice}</p>}
    <section className="mt-6 grid gap-3 md:grid-cols-4">{[{ step: "1", title: "整理議程", ready: agenda.length > 0 }, { step: "2", title: "產生 Brief", ready: !!brief }, { step: "3", title: "私人準備", ready: false }, { step: "4", title: "開始會議", ready: meeting.status === "in_progress" }].map((item) => <div key={item.step} className={`rounded-xl border p-4 ${item.ready ? "border-[#9ddbc8] bg-[#f0fbf8]" : "border-[#e6e6e3] bg-white"}`}><span className="text-xs font-semibold text-[#087e6d]">步驟 {item.step}</span><p className="mt-1 font-medium">{item.title}</p></div>)}</section>
    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-6"><section className="rounded-2xl border border-[#e6e6e3] bg-white p-5 sm:p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div className="flex items-center gap-2"><IconRobot className="text-[#0f9f8a]" size={20} /><h2 className="text-lg font-semibold">會前 Brief</h2></div><p className="mt-2 text-sm leading-6 text-[#787774]">先整理今天要決定什麼、議程順序與待釐清問題。現有後端版本會以本場正式議程建立摘要；文件與歷史決策的 AI 推論仍需後端 AI pipeline。</p></div><button type="button" disabled={busy} onClick={() => void generateBrief()} className="inline-flex shrink-0 items-center gap-1 rounded-lg border border-[#d7e8e5] px-3 py-2 text-sm font-semibold text-[#087e6d] disabled:opacity-60"><IconSparkles size={16} />產生 Brief</button></div>{brief ? <div className="mt-5 rounded-xl bg-[#f7f7f5] p-4"><p className="text-sm leading-6">{brief.summary}</p><ol className="mt-4 space-y-2">{brief.agenda.map((item) => <li key={item.position} className="flex gap-3 text-sm"><span className="font-semibold text-[#087e6d]">{item.position}</span><span>{item.title}{item.description ? `：${item.description}` : ""}</span></li>)}</ol></div> : <div className="mt-5 rounded-xl border border-dashed border-[#d8d8d5] p-5 text-sm text-[#787774]">完成議程後，按下「產生 Brief」來確認會前討論焦點。</div>}</section>
      <section className="rounded-2xl border border-[#e6e6e3] bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">議程與討論順序</h2><p className="mt-1 text-sm text-[#787774]">議程可以先從建立時的範本開始，再針對本場會議調整。</p></div><span className="text-sm text-[#787774]">{agenda.length} 項</span></div><ol className="mt-5 space-y-3">{agenda.map((item) => <li key={item.id} className="flex gap-3 rounded-xl border border-[#ededeb] p-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#e7f7ef] text-sm font-semibold text-[#087e6d]">{item.position}</span><div className="min-w-0 flex-1"><input defaultValue={item.title} onBlur={(event) => event.target.value.trim() && event.target.value.trim() !== item.title && void run(async () => { await updateAgendaItem(id, item.id, { title: event.target.value.trim() }); }, "已更新議程。") } className="w-full bg-transparent text-sm font-medium outline-none" /><select value={item.status} onChange={(event) => void run(async () => { await updateAgendaItem(id, item.id, { status: event.target.value }); }, "已更新議程狀態。") } className="mt-2 bg-transparent text-xs text-[#787774]"><option value="pending">待討論</option><option value="in_progress">討論中</option><option value="completed">已完成</option></select></div><button type="button" disabled={busy} onClick={() => void run(async () => { await removeAgendaItem(id, item.id); }, "已移除議程。") } className="self-center rounded-lg p-2 text-[#787774] hover:bg-red-50 hover:text-red-700" aria-label="移除議程"><IconTrash size={17} /></button></li>)}</ol><form onSubmit={addAgenda} className="mt-4 flex gap-2"><input value={agendaTitle} onChange={(event) => setAgendaTitle(event.target.value)} className="control-primary min-w-0 flex-1" placeholder="新增一個待討論議題" /><button disabled={busy} className="inline-flex items-center gap-1 rounded-lg border border-[#d7e8e5] px-3 text-sm font-medium text-[#087e6d]"><IconPlus size={16} />新增</button></form></section>
      <PersonalSidekickPanel meetingId={id} />
    </div><aside className="space-y-6"><section className="rounded-2xl border border-[#e6e6e3] bg-white p-5"><div className="flex items-center gap-2"><IconUsersGroup className="text-[#0f9f8a]" size={20} /><h2 className="font-semibold">參與者</h2></div><p className="mt-1 text-sm leading-6 text-[#787774]">從此團隊加入本場會議。主持人設定目前尚未有後端欄位，因此不會在前端假裝保存。</p><div className="mt-4 flex gap-2"><select value={selectedMember} onChange={(event) => setSelectedMember(event.target.value)} className="control-primary min-w-0 flex-1 text-sm"><option value="">選擇團隊成員</option>{members.filter((member) => !participants.some((participant) => participant.user_id === member.user_id)).map((member) => <option key={member.user_id} value={member.user_id}>{member.display_name}</option>)}</select><button type="button" disabled={!selectedMember || busy} onClick={() => void run(async () => { await addParticipant(id, { user_id: selectedMember }); setSelectedMember(""); }, "已加入參與者。") } className="rounded-lg bg-[#0f9f8a] px-3 text-sm font-semibold text-white disabled:opacity-50">加入</button></div><div className="mt-4 space-y-2">{participants.map((participant) => <div key={participant.user_id} className="rounded-xl bg-[#f7f7f5] p-3"><p className="text-sm font-medium">{memberName(participant.user_id)}</p><div className="mt-2 flex items-center gap-2"><select value={participant.attendance_status} onChange={(event) => void run(async () => { await updateParticipant(id, participant.user_id, { attendance_status: event.target.value }); }, "已更新出席狀態。") } className="min-w-0 flex-1 bg-transparent text-xs text-[#787774]"><option value="invited">已邀請</option><option value="joined">將出席</option><option value="left">不出席</option></select><button type="button" onClick={() => void run(async () => { await removeParticipant(id, participant.user_id); }, "已移除參與者。") } className="text-xs text-red-700">移除</button></div></div>)}{participants.length === 0 && <p className="rounded-xl bg-[#f7f7f5] p-3 text-sm text-[#787774]">尚未加入參與者。</p>}</div></section>
      <section className="rounded-2xl border border-[#e6e6e3] bg-white p-5"><div className="flex items-center gap-2"><IconRobot className="text-[#0f9f8a]" size={20} /><h2 className="font-semibold">缺席時由 AI 代理</h2></div><p className="mt-2 text-sm leading-6 text-[#787774]">若你無法出席，可預先設定立場與不可逾越的限制。代理只會建立署名提醒，不能替你投票、承諾或做決定。</p><label className="mt-4 flex items-start gap-3 rounded-xl bg-[#f7f7f5] p-3 text-sm"><input type="checkbox" checked={delegateEnabled} onChange={(event) => setDelegateEnabled(event.target.checked)} className="mt-1 accent-[#0f9f8a]" /><span>本場由 AI 依我的事前立場協助提醒</span></label>{delegateEnabled && <form onSubmit={saveDelegate} className="mt-4 space-y-3"><label className="block text-sm font-medium">我的立場<textarea required value={stance} onChange={(event) => setStance(event.target.value)} className={inputClass} placeholder="例如：支持先做小規模試行" /></label><label className="block text-sm font-medium">限制條件<textarea value={constraints} onChange={(event) => setConstraints(event.target.value)} className={inputClass} placeholder="例如：不能超過既定預算" /></label><label className="block text-sm font-medium">必須提醒的情況<textarea value={mustRaise} onChange={(event) => setMustRaise(event.target.value)} className={inputClass} placeholder="例如：若提案忽略維運成本" /></label><button disabled={busy} className="w-full rounded-lg border border-[#d7e8e5] px-3 py-2 text-sm font-semibold text-[#087e6d] disabled:opacity-50">儲存代理規則</button></form>}{delegates.length > 0 && <p className="mt-4 text-xs text-[#087e6d]">本場已有 {delegates.length} 個代理規則。</p>}</section></aside></div>
    <div className="mt-7 flex flex-wrap gap-3"><Link href={`/meetings/${id}/audio-setup`} className="inline-flex items-center gap-2 rounded-lg bg-[#0f9f8a] px-4 py-2.5 text-sm font-semibold text-white">設定收音 <IconArrowUpRight size={17} /></Link><Link href={`/meetings/${id}/addon`} className="rounded-lg border border-[#dededb] px-4 py-2.5 text-sm font-medium hover:bg-[#f7f7f5]">預覽 Meet Add-on</Link></div>
  </AppShell>;
}
